### ISSUE TITLE
meer contrast voor weergave links

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#13]
assigned @JorisLambrechts 

Kan je de links een blauwe contrastrijke kleur geven zodat ze beter opvallen. 
![capture](https://cloud.githubusercontent.com/assets/3798589/10342420/4b3ed2ea-6d19-11e5-8cd9-7c3952b935da.JPG)

**Comment by JorisLambrechts** [comment]
alle links, of alleen die in de simple pages
