### ISSUE TITLE
Zoeken op object toevoegen

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#16]
assigned @JorisLambrechts 

Wanneer de gebruiker op Magister Dixit Collection klikt in navigatie, krijgen ze direct de simple search box te zien. 
![capture](https://cloud.githubusercontent.com/assets/3798589/10365210/da6b6cc8-6dc1-11e5-89e7-dd2050f87870.JPG)

Zoekresultaten al beperken zodat je enkel objecten uit de collectie Magister Dixit Project krijgt. Tenzij we dit later nog eenvoudig kunnen aanpassen als er nieuwe projecten opgestart worden. 

Kan je naast of onder de zoekbox een link voorzien die verwijst naar de simple page 'search-tips'.

**Comment by JorisLambrechts** [comment]
Mag die link dan direct naar de solr-pagina met zoekresultaten (en een search box)?

**Comment by roxannewyns** [comment]
ja

**Comment by JorisLambrechts** [comment]
aangepast in admin (de rest zit in #17)
