### ISSUE TITLE
link naar viewer achter thumbnail show pagina steken

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#22]

**Comment by roxannewyns** [comment]
De mirador viewer zou moeten opengaan ipv van mets viewer

**Comment by JorisLambrechts** [comment]
Je bedoelt dan de link die in de metadata meegegeven wordt (en nu al bij 'IMAGES' staat)? Want nu heb ik gewoon de pid in de depot.lias.be...&mirador=true link geplakt en dat werkt dus niet bij FL-nummers bijvoorbeeld (redirect dus naar de mets viewer)
