### ISSUE TITLE
carrousel mag niet hard gecodeerd zijn

### ISSUE THREAD

**Issue by samalloing** [libis/lectio#25]
De carrousel moet gebruik maken van shortcode (ofwel een bestaande shortcode ofwel een eigen ontwikkelde shortcode). De afbeeldingen gebruikt in de shortcode moet configureerbaar zijn (liefst via de imagemanager, via items van een bepaald type is ook goed)

**Comment by JorisLambrechts** [comment]
Afbeeldingen zitten in de images map dus die zijn iig al aanpasbaar (bg.jpeg, bg2.jpeg en bg3.jpeg).

Ik kan er een shortcode voor aanmaken maar dan enkel in een plugin, de bestaande carrousel shortcode was niet bruikbaar in dit geval (het is de achtergrond die verandert)

Omdat het een achtergrond is (achter de main content) moet de code ook in de header.php staan of iig niet in de content (vb simple page) en is die bijgevolg niet aanpasbaar voor de gebruiker waardoor een shortcode hier wellicht geen meerwaarde opleverd.

Oorspronkelijk was het ook gewoon maar een afbeelding en geen caroussel.

**Comment by samalloing** [comment]
De shortcode is denk ik wel zinvol aangezien er kan geselecteerd worden welke afbeeldingen getoond moeten worden in de caroussel. Als ze er morgen 4 nodig hebben ipv 3 dan mogen wij de code weer aanpassen. De shortcode moeten wij dan éénmalig plaatsen in de header en de rest kan de shortcode aanpassen. Het is ook herbruikbaar voor volgende projecten
