### ISSUE TITLE
Maak van de footer een simplepage

### ISSUE THREAD

**Issue by samalloing** [libis/lectio#26]
De footer zou een simple page moeten om de logo's te tonen. de andere info mag nog getoond worden via de code in de footer

**Comment by JorisLambrechts** [comment]
De footer tekst komt uit de admin -> Appearance -> Themes -> Configure theme en dan het veld 'footer text'

**Comment by samalloing** [comment]
Ja het gaat mij vooral over de simplepage en de logo's. Ik bedoel dat de tekst mag blijven komen van die plaats. Dat hoeft niet in een simplepage
