### ISSUE TITLE
ontbrekende afbeelding geeft exception

### ISSUE THREAD

**Issue by samalloing** [libis/lectio#27]
Als je echo img gebruikt moet je de exception opvangen als de afbeelding niet bestaat of als dat gaat nakijken of de afbeelding bestaat, want nu krijg je exceptions te zien in de browser

**Comment by JorisLambrechts** [comment]
Ik kan ook gewoon de WEB_THEME en dergelijke gebruiken ipv van img(), anders moet er bij elke img() een try en catch komen wat nogal omslachtig is mss. 

Voor de controle of een file bestaat moet ik ook al het path samenstellen dus dan kan ik het mss ook gewoon beter ineens gebruiken. Als de afbeelding dan niet bestaat komt er gewoon niks, dat is logischer gedrag lijkt mij.

img() controleert ook of het path bestaat trouwens en gooit de exception indien dat niet het geval is

**Comment by samalloing** [comment]
Er wordt trouwens een InvalidArgumentException exception gethrowed
