### ISSUE TITLE
solr heeft geen dublin core extended velden

### ISSUE THREAD

**Issue by samalloing** [libis/lectio#31]
Er is iets mis met de installatie van solr aangezien die geen dublin core extended heeft. Hetzelfde probleem doet zich voor bij andere omeka solrs

**Comment by JorisLambrechts** [comment]
Volgorde van installatie is belangrijk: dublin core extended moet voor solr geinstalleerd worden anders kunnen de extra velden niet gebruikt worden als facet.

Solr doet bij de installatie gewoon een keer $elements->findAl().
