### ISSUE TITLE
opmaak - home page

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#4]
assigned @JorisLambrechts 

*
Kader met tekst 'Leuven Centre for the Study of the Transmission of Texts and Ideas in Antiquity, the Middle Ages and the Renaissance' op homepage iets kleiner maken. 
Bovenaan in het tekstkadert LECTIO plaatsen.
'Leuven Centre for the Study of the Transmission of Texts and Ideas in Antiquity, the Middle Ages and the Renaissance' eronder als subtitel in een iets kleiner lettertype.

*
Aanpassen volgorde & text 6 iconen. Zorg ook dat de hoofdletters in de zin er allemaal staan zoals hieronder.
3 iconen bovenaan, in volgende volgorde: Laboratory for Text Editing | Conferences | Lectio Chair
3 iconen bovenaan, in volgende volgorde: Magister Dixit Project | Lectures | Lectio Series

*
Link achter iconen doorverwijzen naar volgende pagina's:
Laboratory for Text Editing naar: /lectio/laboratory-for-text-editing
Conferences naar: /lectio/conferences
Lectio Chair naar: /lectio/lectio-chair
Magister Dixit Project naar: /lectio/magister-dixit-project
Lectures naar: /lectio/lectures
Lectio Series naar: /lectio/lectio-series

*
Kan je van de volledige banner een roterende fotoreeks maken (zie vb. Illuminare http://www.illuminare.be/), of veel werk?

**Comment by JorisLambrechts** [comment]
Gewoon wisselende fotos is niet veel werk, maar als er ook tekst en links op moeten, moet ik het design aanpassen.

Die achtergrond staat ook op alle pagina's dus het zal dan ook op alle pagina's wisselen.

**Comment by JorisLambrechts** [comment]
https://github.com/libis/lectio/commit/c51e6055ffffd52cfc5d776367b6ee64837ae197

**Comment by JorisLambrechts** [comment]
ik heb de caroussel geïmplementeerd maar zal ik zelf afbeeldingen zoeken of gaan ze die aanleveren
