### ISSUE TITLE
2 URLs op home page verwijzen nog naar heron-net adres

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#40]
2 van de links op de homepagina verwijzen nog naar het heron-net adres. Deze moeten net als de andere links verwijzen naar het nieuwe adres lectio.ghum.kuleuven.be. Ik krijg het niet aangepast door de simple page opnieuw te saven. Die andere 4 kaders gebruiken wel de juiste URL. 

![untitled](https://cloud.githubusercontent.com/assets/3798589/15324525/1bd7b6ba-1c47-11e6-9ad0-83d5ad349e64.png)

**Comment by JorisLambrechts** [comment]
dit is ok (via admin)
