### ISSUE TITLE
Alma sync - aanpassingen mapping

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#41]
Ik heb nog eens een extra testje gedaan met record dat al in Omeka zat.
/lectio_test/items/show/250 bestond al, maar heb ik even het alma ID nummer aangepast om te voorkomen dat het overschreven werd.
/lectio_test/items/show/298 is hetzelfde record na de synchronisatie

3 issues:

Source ontbreekt 

'Content' gaat in de mapping naar het Dublin Core veld 'Table of contents'. Table of contents verschijnt echter niet in de front-end. Ofwel mapping aanpassen dat het naar het veld 'Content' gaat, ofwel regel toevoegen om 'Table of contents' te laten verschijnen in front-end als 'Content'

Idem 'Other titles'. Dit gaat nu naar 'Alternative titles'. Op zich is dit goed, maar dit veld verschijnt ook niet in de front-end.

**Comment by JorisLambrechts** [comment]
- Source is toegevoegd (stond verkeerd in de code)
- Content wijst in public naar Item Type Metadata Content
- Table Of Contents wees naar Details op de publieke pagina maar ipv Dublin Core Table Of Contents stond er Item Type Metadata Table of contents (dit heb ik nu aangepast naar Dublin Core)
- Other titles wijst nu naar Dublin Core Alternative Title

**Comment by roxannewyns** [comment]
De alternative titles moeten nog opgeslitst worden. Nu worden ze achter elkaar gezet, gescheiden door ;
![capture](https://cloud.githubusercontent.com/assets/3798589/25951982/adb6efb4-365f-11e7-86e1-8fd5d73a37cc.JPG)
![capture_2](https://cloud.githubusercontent.com/assets/3798589/25951981/adaefef8-365f-11e7-8597-abd367776c8d.JPG)
