### ISSUE TITLE
Alma sync - URL naar image viewer aanpassen

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#42]
Blijkbaar zijn er nog veel oude PIDs in gebruik in Alma. Op zich vreemd, want ik dacht dat dit allemaal was aangepast naar IE nummers.
Hierdoor werkt de huidige URL niet naar de afbeelding in de viewer
http://depot.lias.be/delivery/DeliveryManagerServlet?dps_pid=3567213&mirador=true
moet namelijk 
http://resolver.libis.be/3567213/representation zijn.
nkel d.m.v. de resolver URL kan je oude PIDs terugvinden en op het IE object terecht komen. 
Kan jij dit aanpassen a.u.b. Dit mag een algemene regel zijn. de resolver URL kan best overal gebruikt worden.

**Comment by JorisLambrechts** [comment]
De link wordt opgeslagen bij het opslaan van een file dus in de praktijk is dat bij een import via de plugin bijvoorbeeld. Item 298 heb ik als test gebruikt.
