### ISSUE TITLE
Lay-out

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#43]
Een detail, maar ik zie dat meerdere professoren op 1 lijn staan. Net zoals bij de andere best op een nieuwe lijn zetten. 

Bierens, Simon (professor primarius); Lauwkens, Laurentius (professor secundarius)
wordt
Bierens, Simon (professor primarius)
Lauwkens, Laurentius (professor secundarius)

**Comment by JorisLambrechts** [comment]
Er zijn nog een aantal velden met een ';' als delimiter ipv een nieuwe lijn, zal ik ze allemaal dan op een nieuwe lijn zetten. vb provenance, student, date, call number

**Comment by roxannewyns** [comment]
ah, laat anders maar. Ik weet niet zeker waar ze het wel of niet willen. Ze zullen het wel laten weten als het anders willen.
