### ISSUE TITLE
browse item page geeft untitled hoewel title aanwezig is

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#44]
![image](https://user-images.githubusercontent.com/3798589/28212875-d2943276-68a3-11e7-961c-514d8a9b3ee9.png)

![image](https://user-images.githubusercontent.com/3798589/28212885-df6cd69c-68a3-11e7-9ed2-c96dad764aa0.png)

**Comment by JorisLambrechts** [comment]
da2698fbd57276e25f0f9e41159336a922cfd069
