### ISSUE TITLE
afbeelding laden in image manager lukt niet

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#6]
assigned @JorisLambrechts 

Als ik beelden sleep naar de image manager laden ze niet op.
Kan je me ineens ook het juiste image path geven voor het toevoegen van afbeeldingen aan simple pages.

**Comment by JorisLambrechts** [comment]
image manager werkt nu wel (moest de image folder nog uit de git repository halen)

**Comment by JorisLambrechts** [comment]
vb url: /lectio/themes/lectio/images/KULeuven-logo.png
