### ISSUE TITLE
news items en event items implementeren

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#7]
assigned @JorisLambrechts 

News en Event items laten verschijnen op home page en project page.

Items van het itemtype 'News Homepage' moeten onder news items op de home page verschijnen
Items van het itemtype 'Event Homepage' moeten onder event items op de home page verschijnen

Items van het itemtype 'News Magister Dixit project'' moeten onder news items van dat project verschijnen, dus hier /lectio/magister-dixit-project
Items van het itemtype 'Event Magister Dixit project'' moeten onder event items van dat project verschijnen, dus hier /lectio/magister-dixit-project

Metadata om te tonen:
Title
Description

Sorteren van nieuw (bovenaan lijst) naar oud (onderaan lijst).
Sorteren op de door de partner ingevoerde datum waarde in het DC metadataveld 'Date' of beter in een volledig nieuw veld? Dat heb ik nog niet aangemaakt voor die types. Gelieve het datum formaat te specificeren in de beschrijving. 

Op de Home page staat er onder News en Events een lees meer knop. Deze moet doorverwijzen naar alle items van dat type als het er meer dan 3 zijn. Bij de projectpagina Magister ... staat dit er niet. Best deze optie ook daar toevoegen denk ik.

**Comment by roxannewyns** [comment]
aanpassing naar overleg.
slechts 2 itemtypes: news, event
volgende tags om aan te duiden waar het news of event item moet verschijnen. 
![capture](https://cloud.githubusercontent.com/assets/3798589/10075724/a2112420-62d7-11e5-98db-d7bab1e9bf17.JPG)

**Comment by roxannewyns** [comment]
Op de pagina /lectio/magister-dixit-project verschijnen de juiste nieuws en event items nog niet. Deze worden aangeduid met bovenstaande tag 'Magister Dixit'
![capture](https://cloud.githubusercontent.com/assets/3798589/10220377/60e0f276-6847-11e5-878e-933d1f49f628.JPG)

**Comment by roxannewyns** [comment]
Op wat worden ze nu gesorteerd? Meest recent aangemaakte bovenaan? Wat als er een item gewijzigd wordt, gaat dit dan een gevolg hebben in de rangschikking?

**Comment by JorisLambrechts** [comment]
Ik gebruik de shortcodes van omeka, maar er loopt nog het een en ander mis zie ik dus ik vermoed dat die nog niet op punt staan. Zal sorteren op recentst aangemaakt, dan maken wijzingen achteraf niets uit.

**Comment by JorisLambrechts** [comment]
nu juiste shortcode (te zien en eventueel aan te passen op simple page /magister-dixit-project): [items item_type="News" tags="Magister Dixit" num=3 sort=added order=d] 

ontbrekende item_type filter toegevoegd -> https://github.com/libis/lectio/commit/a3d22eb67ebacafdd387c4dbf5948fc25d7cda55

sortering op datum 'toegevoegd'
