### ISSUE TITLE
facet browsing

### ISSUE THREAD

**Issue by roxannewyns** [libis/lectio#9]
assigned @JorisLambrechts 

De beeldbank komt onder Magister Dixit Collection 'lectio/magister-dixit-collection' pagina.
Voorlopig is het idee eerder dat ze nog een korte intro tekst voorzien met daaronder de zoekfunctie.
De tekst moeten ze zelf kunnen aanpassen. 
Simple search box voorzien. 
Facets voorlopig: Subject, Source, Contributor, Date, Type, Coverage
Laat dezelfe waarden zien in het overzicht van de zoekresultaten.

**Comment by roxannewyns** [comment]
Ook een reset all filters knop voorizen

**Comment by JorisLambrechts** [comment]
dat zijn dublin core velden?

**Comment by roxannewyns** [comment]
Die wel. Ik wil het anders later wel aanpassen hoor, maar had het alvast doorgegeven zodat je een tekst resultaat kon zien.
